require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

pod 'OpenSSL-Universal', '~>1.0.2.20'

platform :ios, '10.0'

target 'CafeApp' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

  #target 'CafeAppTests' do
  #  inherit! :complete
    # Pods for testing
  #end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'CafeApp-tvOS' do
  # Pods for CafeApp-tvOS

  target 'CafeApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end