export default {
    SET_LOADING: 'SET_LOADING',
    SET_SELECTEDFEATUREINDEX: 'SET_SELECTEDFEATUREINDEX',
    SET_SELECTEDFEATURE: 'SET_SELECTEDFEATURE',
    SET_NORMALCARD: 'SET_NORMALCARD',
    SET_SELECTEDSUBFEATURES: 'SET_SELECTEDSUBFEATURES',
    SET_SELECTEDSUBFEATUREINDEX: 'SET_SELECTEDSUBFEATUREINDEX'
}